steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/kubernetes-428622/container2", "."]

  # Step 2: Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/kubernetes-428622/container2"]

  # Step 3: Get credentials and apply Kubernetes deployment
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials assignment-cluster --zone us-central1-a &&
        kubectl apply -f deployment-container2.yaml

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "set"
      - "image"
      - "deployment/assignment-deployment-container2"
      - "container2=gcr.io/kubernetes-428622/container2:$SHORT_SHA"

images:
  - "gcr.io/kubernetes-428622/container2"

options:
  logging: CLOUD_LOGGING_ONLY
