apiVersion: v1
kind: Service
metadata:
  name: service-container2
spec:
  type: LoadBalancer
  selector:
    app: test-assignment
    component: container2
  ports:
    - name: http-ports
      protocol: TCP
      port: 8000
      targetPort: 8000
